### ISSUE TITLE
graph_tools.Read_edges treats comments as edges

### ISSUE THREAD

**Issue by linzhp** [csesha/patterns-in-python#1]
@csesha 

The first four lines in the graph files are often comments, but `graph_tools.Read_edges` treats them as edges. To see the bug, just let it read the following one-edge graph:

```
# Directed graph (each unordered pair of nodes is saved once): Amazon0312.txt 
# Amazon product co-purchaisng network from March 12 2003
# Nodes: 400727 Edges: 3200440
# FromNodeId    ToNodeId
0   1
```

It would report 5 raw edges. The following is a more robust way of reading a graph file:

``` python
import re
g = Graph()
with open(file, 'r') as graph_file:
    for line in graph_file:
        if not line.startswith('#'):
            nodes = re.split('\s+', line.strip(), 1)
            g.add_edge(int(nodes[0]), int(nodes[1]))

```

**Comment by csesha** [comment]
Thanks Zhongpeng! Yes, this is definitely a bug. Could you fix it? If not, let me know.
